[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "hickathon6"
version = "1.0.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = []

[tool.hatch.build.targets.wheel]
packages = ["src"]


[project.scripts]
hickathon6 = "src.main:main"